name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Go bits
      run: echo !!! Not done yet !!!
    - name: Build
      run: echo !!! Not done yet !!!
    - name: Run tests
      run: echo !!! Not done yet !!!
